const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { roots } = require('../home')
const library = require('../library')

const fakeHome = () => fs.mkdtempSync(path.join(os.tmpdir(), 'tetra-home-'))

test('~/Drive becomes ~/Tetra by renaming, with every file where it was', () => {
  const home = fakeHome()
  fs.mkdirSync(path.join(home, 'Drive', 'Photos', 'DCIM', 'Camera'), { recursive: true })
  fs.mkdirSync(path.join(home, 'Drive', 'Drive', 'Documents'), { recursive: true })
  fs.writeFileSync(path.join(home, 'Drive', 'Photos', 'DCIM', 'Camera', 'a.jpg'), 'photo')
  fs.writeFileSync(path.join(home, 'Drive', 'Drive', 'Documents', 'plan.txt'), 'doc')
  const r = roots(home)
  assert.equal(r.photos, path.join(home, 'Tetra', 'Photos'))
  assert.equal(r.files, path.join(home, 'Tetra', 'Files'))
  assert.equal(fs.readFileSync(path.join(r.photos, 'DCIM', 'Camera', 'a.jpg'), 'utf8'), 'photo')
  assert.equal(fs.readFileSync(path.join(r.files, 'Documents', 'plan.txt'), 'utf8'), 'doc')
  assert.ok(!fs.existsSync(path.join(home, 'Drive')))
  assert.deepEqual(roots(home).moved, [], 'and only once')
  fs.rmSync(home, { recursive: true })
})

test('an interrupted move finishes on the next start', () => {
  const home = fakeHome()
  fs.mkdirSync(path.join(home, 'Tetra', 'Drive'), { recursive: true })
  fs.mkdirSync(path.join(home, 'Tetra', 'Photos'))
  assert.equal(roots(home).moved.length, 1)
  assert.ok(fs.existsSync(path.join(home, 'Tetra', 'Files')))
  fs.rmSync(home, { recursive: true })
})

test('a ~/Drive holding anything else is left alone and still used', () => {
  const home = fakeHome()
  fs.mkdirSync(path.join(home, 'Drive', 'Photos'), { recursive: true })
  fs.mkdirSync(path.join(home, 'Drive', 'Someone else'))
  const r = roots(home)
  assert.deepEqual(r.moved, [])
  assert.match(r.note, /Someone else/)
  assert.equal(r.photos, path.join(home, 'Drive', 'Photos'))
  assert.ok(fs.existsSync(path.join(home, 'Drive', 'Someone else')))
  fs.rmSync(home, { recursive: true })
})

test('a fresh install uses ~/Tetra; a hidden QA copy never moves anything', () => {
  const home = fakeHome()
  assert.equal(roots(home).photos, path.join(home, 'Tetra', 'Photos'))
  fs.mkdirSync(path.join(home, 'Drive', 'Photos'), { recursive: true })
  const r = roots(home, { migrate: false })
  assert.deepEqual(r.moved, [])
  assert.ok(fs.existsSync(path.join(home, 'Drive', 'Photos')))
  fs.rmSync(home, { recursive: true })
})

test('a missing or empty Photos folder is never read as "every photo was deleted"', async () => {
  const tmp = fakeHome()
  const db = library.open(path.join(tmp, 'data'))
  const add = db.prepare(`INSERT INTO media(path, sha256, mime, is_video, size, mtime, taken_at) VALUES(?, ?, 'image/jpeg', 0, 1, 1, 1)`)
  for (let i = 0; i < 25; i++) add.run(`p${i}.jpg`, String(i).padStart(64, '0'))
  await assert.rejects(library.scan(db, path.join(tmp, 'gone'), path.join(tmp, 'data')), /missing/)
  fs.mkdirSync(path.join(tmp, 'empty'))
  await assert.rejects(library.scan(db, path.join(tmp, 'empty'), path.join(tmp, 'data')), /empty/)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM media').get().n, 25, 'the library is untouched')
  db.close()
  fs.rmSync(tmp, { recursive: true })
})
