const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('drive', {
  info: () => ipcRenderer.invoke('library:info'),
  list: () => ipcRenderer.invoke('library:list'),
  folders: {
    list: () => ipcRenderer.invoke('folders:list'),
    set: (name, included) => ipcRenderer.invoke('folders:set', name, included),
  },
  scan: () => ipcRenderer.invoke('library:scan'),
  show: id => ipcRenderer.invoke('library:show', id),
  openMap: (lat, lon) => ipcRenderer.invoke('open-map', lat, lon),
  editorLoad: id => ipcRenderer.invoke('editor:load', id),
  editorSave: (id, bytes, mode) => ipcRenderer.invoke('editor:save', id, bytes, mode),
  favorite: (shas, on) => ipcRenderer.invoke('photos:favorite', shas, on),
  trash: ids => ipcRenderer.invoke('photos:trash', ids),
  places: () => ipcRenderer.invoke('photos:places'),
  moveTo: (ids, dest) => ipcRenderer.invoke('photos:moveTo', ids, dest),
  collections: () => ipcRenderer.invoke('collections:list'),
  createCollection: name => ipcRenderer.invoke('collections:create', name),
  deleteCollection: id => ipcRenderer.invoke('collections:delete', id),
  setCollectionHidden: (id, hidden) => ipcRenderer.invoke('collections:hide', id, hidden),
  trashList: () => ipcRenderer.invoke('trash:list'),
  trashRestore: ids => ipcRenderer.invoke('trash:restore', ids),
  trashEmpty: () => ipcRenderer.invoke('trash:empty'),
  viewSettings: () => ipcRenderer.invoke('settings:view'),
  setViewSetting: (key, on) => ipcRenderer.invoke('settings:setView', key, on),
  members: id => ipcRenderer.invoke('collections:members', id),
  setMembership: (id, shas, member) => ipcRenderer.invoke('collections:set', id, shas, member),
  deleteFromDrive: (id, shas) => ipcRenderer.invoke('drive:delete', id, shas),
  notes: (method, ...args) => ipcRenderer.invoke('notes:call', method, ...args),
  files: {
    root: () => ipcRenderer.invoke('files:root'),
    call: (method, ...args) => ipcRenderer.invoke('files:call', method, ...args),
    open: rel => ipcRenderer.invoke('files:open', rel),
    reveal: rel => ipcRenderer.invoke('files:reveal', rel),
  },
  vault: {
    status: () => ipcRenderer.invoke('vault:status'),
    setup: pass => ipcRenderer.invoke('vault:setup', pass),
    unlock: pass => ipcRenderer.invoke('vault:unlock', pass),
    lock: () => ipcRenderer.invoke('vault:lock'),
    list: () => ipcRenderer.invoke('vault:list'),
    hide: ids => ipcRenderer.invoke('vault:hide', ids),
    restore: ids => ipcRenderer.invoke('vault:restore', ids),
  },
  history: options => ipcRenderer.invoke('history:list', options),
  purgatory: {
    settings: () => ipcRenderer.invoke('purgatory:settings'),
    set: changes => ipcRenderer.invoke('purgatory:set', changes),
    setLocation: driveId => ipcRenderer.invoke('purgatory:setLocation', driveId),
  },
  sync: {
    status: () => ipcRenderer.invoke('sync:status'),
    pair: () => ipcRenderer.invoke('sync:pair'),
    forget: id => ipcRenderer.invoke('sync:forget', id),
    files: (what, options) => ipcRenderer.invoke('sync:files', what, options),
    setDevice: (id, changes) => ipcRenderer.invoke('sync:setDevice', id, changes),
    setSelf: changes => ipcRenderer.invoke('sync:setSelf', changes),
    completeSetup: id => ipcRenderer.invoke('sync:completeSetup', id),
    drives: () => ipcRenderer.invoke('sync:drives'),
    inspectDrive: uuid => ipcRenderer.invoke('sync:inspectDrive', uuid),
    addDrive: drive => ipcRenderer.invoke('sync:addDrive', drive),
    backUpToDrive: id => ipcRenderer.invoke('sync:backUpToDrive', id),
    onDriveProgress: fn => { const l = (_, p) => fn(p); ipcRenderer.on('drive-progress', l); return () => ipcRenderer.off('drive-progress', l) },
    setConnection: (id, content, rules) => ipcRenderer.invoke('sync:setConnection', id, content, rules),
    movePreview: (id, options) => ipcRenderer.invoke('sync:movePreview', id, options),
    setDriveRules: (id, rules) => ipcRenderer.invoke('sync:setDriveRules', id, rules),
    offloadPlan: id => ipcRenderer.invoke('sync:offloadPlan', id),
    moveToDrive: (id, options) => ipcRenderer.invoke('sync:moveToDrive', id, options),
    onMoveProgress: fn => { const l = (_, p) => fn(p); ipcRenderer.on('move-progress', l); return () => ipcRenderer.off('move-progress', l) },
    onOffer: fn => { const l = (_, id) => fn(id); ipcRenderer.on('offload-offer', l); return () => ipcRenderer.off('offload-offer', l) },
    onReceived: fn => { const l = () => fn(); ipcRenderer.on('sync-received', l); return () => ipcRenderer.off('sync-received', l) },
  },
  documents: {
    start: () => ipcRenderer.invoke('documents:start'),
    rescan: () => ipcRenderer.invoke('documents:rescan'),
    nextReview: () => ipcRenderer.invoke('documents:nextReview'),
    answer: (sha, answer) => ipcRenderer.invoke('documents:answer', sha, answer),
    set: (sha, on) => ipcRenderer.invoke('documents:set', sha, on),
  },
  people: {
    status: () => ipcRenderer.invoke('people:status'),
    start: () => ipcRenderer.invoke('people:start'),
    rescan: () => ipcRenderer.invoke('people:rescan'),
    pause: () => ipcRenderer.invoke('people:pause'),
    list: () => ipcRenderer.invoke('people:list'),
    forgotten: () => ipcRenderer.invoke('people:forgotten'),
    setHidden: (id, hidden) => ipcRenderer.invoke('people:setHidden', id, hidden),
    shas: id => ipcRenderer.invoke('people:shas', id),
    names: () => ipcRenderer.invoke('people:names'),
    rename: (id, name) => ipcRenderer.invoke('people:rename', id, name),
    faces: id => ipcRenderer.invoke('people:faces', id),
    setCover: (id, faceId) => ipcRenderer.invoke('people:setCover', id, faceId),
    merge: (source, target) => ipcRenderer.invoke('people:merge', source, target),
    detach: (id, shas) => ipcRenderer.invoke('people:detach', id, shas),
    undoMerge: undo => ipcRenderer.invoke('people:undoMerge', undo),
    mergeHistory: id => ipcRenderer.invoke('people:mergeHistory', id),
    restoreMerge: id => ipcRenderer.invoke('people:restoreMerge', id),
    nextReview: () => ipcRenderer.invoke('people:nextReview'),
    answer: (faceId, personId, answer) => ipcRenderer.invoke('people:answer', faceId, personId, answer),
    onProgress: fn => { const l = (_, p) => fn(p); ipcRenderer.on('people-progress', l); return () => ipcRenderer.off('people-progress', l) },
  },
  onScanProgress: fn => {
    const listener = (_, p) => fn(p)
    ipcRenderer.on('scan-progress', listener)
    return () => ipcRenderer.off('scan-progress', listener)
  },
})
